name: Gerar localizacoes.json

on:
  schedule:
    - cron: '*/5 * * * *'  # A cada 5 minutos
  workflow_dispatch:       # Permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositório
      uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Instalar dependências
      run: |
        pip install requests beautifulsoup4

    - name: Rodar scraping e gerar JSON
      run: python api/api.py

    - name: Commit e push do JSON
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions"
        git add public/localizacoes.json
        git commit -m "Atualizando localizacoes.json" || echo "Nada novo"
        git push
